### ISSUE TITLE
Doesn't have any effect in Internet Explorer

### ISSUE THREAD

**Issue by freeform-sg** [twomice/com.joineryhq.profcond#11] opened 2020-02-05 20:31 UTC
We go this up and working fine in Chrome, however the client noticed none of the changes were reflected in Internet Explorer (Edge). I confirmed this on Windows 10 running Edge 18.

Running only 3 simple onload actions:

```
'selectors' => array (
  $dietary_field => array( 
    'before' => '#pricesetTotal',
  ),
  $empty_section => array( 
     'display' => 'hide',
  ),
),
'profiles' => array (
  $details_profile => array( 
    'before' => '#priceset',
  ),
),
```

**Comment by twomice** [comment] 2020-02-05 20:52
Thank you for the report. By chance, could you provide a public-facing URL for the relevant page? Feel free to email me directly at the address in my profile, if you prefer greater privacy for that URL.

**Comment by freeform-sg** [comment] 2020-02-05 20:56
Thanks - the form requires an account on the site, I'll need to set-up temp access for you.

**Comment by twomice** [comment] 2020-02-05 20:59
If you don't mind, that would be very helpful so I can examine the problem in action.  If you need to share sensitive site credentials, you can post a secure message at https://joineryhq.com/message (this avoids sending sensitive data by email).

**Comment by twomice** [comment] 2020-02-06 17:53
Email received, looking at the form now.

**Comment by twomice** [comment] 2020-02-06 18:20
Hi @freeform-sg . I'm having trouble reproducing the bad behavior, but the closest I've tried to your platform is my Edge 79.0.309.71 in Windows 7.

I'm not clear what browser you're using; could you provide a screenshot of the "Help > About" screen which states the browser version details?

**Comment by twomice** [comment] 2020-02-07 18:37
FYI, I think attachments in email replies aren't being in the github ticket, so I don't see the screenshot; but your description is clear enough for now. I'll give it a shot and get back with you.

**Comment by freeform-sg** [comment] 2020-03-30 19:30
Hi Allen,

I've added the missing screenshot to my previous message (sorry for the delay). This issue is labeled 'needs info', do you need any more information from me at this time? 

By the way, a few things have been added to the code since I originally posted this, there are a few more actions that have been implemented, though the original issue persists.

Thanks!

**Comment by twomice** [comment] 2020-03-30 20:03
Thanks @freeform-sg . Got it, and I've removed that tag

**Comment by BillCrabtree** [comment] 2020-04-14 14:22
IE 11 shows a syntax error in the profcondSelect2.js file.  I have not been able to locate the error in the code.

**Comment by lucky091588** [comment] 2020-07-15 18:13
I reproduce the error with certain steps in version 1.4.
There is no error on version 1.5-rc1 using the same steps.

The issue is resolved in version 1.5-rc1.

**Comment by twomice** [comment] 2020-07-15 19:58
Thanks @lucky091588 . @freeform-sg It's been a while since you posted, but if you're still dealing with this issue, could you try upgrading to v 1.5.0-rc1 (currently the latest commit on master) and confirm whether that fixes the issue?

**Comment by BillCrabtree** [comment] 2020-07-15 20:36
Thank you.  I will take a look as soon as I have an opportunity

**Comment by BillCrabtree** [comment] 2020-07-15 20:37
I will as soon as I can.  Thank you :)

**Comment by freeform-sg** [comment] 2020-07-17 13:16
Thanks @twomice I'll take a look

**Comment by twomice** [comment] 2020-08-28 17:22
I'm going to go ahead and close this, considering [comments above](https://github.com/twomice/com.joineryhq.profcond/issues/11#issuecomment-658922091) and on the basically equivalent issue #13 . Please feel free to re-open if you find this very issue persists, or of  course open a new ticket at any time.

**Closed by twomice** 2020-08-28 17:22 UTC
Labels: bug

**Comment by freeform-sg** [comment] 2020-10-05 20:27
@twomice thanks for your work on this, apologies for the late reply, I finally got around to testing this and confirm it's working as expected now in Edge 18 on Windows 10. Cheers.

**Comment by twomice** [comment] 2020-10-05 21:43
Thanks @freeform-sg !
