### ISSUE TITLE
Required hidden fields break on newer versions of Civi

### ISSUE THREAD

**Issue by MegaphoneJon** [twomice/com.joineryhq.profcond#18] opened 2020-10-06 19:00 UTC
Newer versions of Civi have re-enabled jQuery Validate, so the current approach of handling "required and hidden" fields no longer works.  That's a PHP-level fix, and jQuery Validate runs before page submission, and in fact blocks page submission.

I have a fix, but I need to reconcile my fork against master first.  I'll submit it soon.

**Comment by twomice** [comment] 2020-10-06 19:06
Thanks @MegaphoneJon Looking forward to your PR!

**Comment by twomice** [comment] 2020-10-07 16:33
@MegaphoneJon can you guess about what version of civicrm this started to become an issue?

**Comment by MegaphoneJon** [comment] 2020-10-07 17:01
Looks like 5.24: https://github.com/civicrm/civicrm-core/pull/16494/commits

**Comment by twomice** [comment] 2020-10-07 22:23
Thansk

**Comment by twomice** [comment] 2020-10-12 15:51
Hi @MegaphoneJon I'm not able to reproduce the problem in civicrm 5.29.1. My steps are:

1. Create a profile with a required field (example name "Field A"); attach this profile to Contribution Page A.
2. Configure Profile Conditional rules to hide this field in certain circumstances on Contribution Page A.
3. Open Contribution Page A in a live contribution, and edit field values to hide Field A, per rules configured in step 2.
4. Click Submit. 

Expected bad behavior: Based on the OP, I thought I'd get an on-page (pre-submit) "required field missing" error message, and that the form submission would be canceled.

Observed correct behavior: The form is submitted successfully, with no "required field missing" error for Field A. 

Can you suggest some steps that would demonstrate the bad behavior? Your description totally makes sense, so I was really surprised not to see the bad behavior. But before merging I'd like to verify the bad behavior AND that the PR actually fixes it. Thanks!

**Comment by twomice** [comment] 2020-12-07 18:15
Ticket is on hold, pending response from OP.

**Comment by twomice** [comment] 2021-05-26 20:37
@MegaphoneJon We're now seeing this on some sites (whereas previously I said I couldn't reproduce). You mentioned you might have a fix -- would you be able to share any thoughts / notes / rough code (or even a PR) along those lines?

**Comment by MegaphoneJon** [comment] 2021-05-26 20:57
Well, sorry you're experiencing it, but glad you have some time to look at this since I clearly did not :(  But yes - I did write a fix, see here: https://github.com/MegaphoneJon/com.joineryhq.profcond/commit/f963a914dd74fbebd377200622739a3ad2157782.  I'll PR that and you can do what you will.

**Comment by twomice** [comment] 2021-05-26 23:21
Reference PR #20

**Comment by twomice** [comment] 2021-08-02 18:38
Fixed in PR #20.

**Closed by twomice** 2021-08-02 18:38 UTC
